"""Writes results/reports/phase1c_report.md from the measured JSON/CSV artefacts of 1C (every number is read from a file; the prose is the only hand-written part).
Usage: python -m scaleup.make_report"""
from __future__ import annotations

import paths as RP

import csv
import json
from collections import defaultdict
from pathlib import Path

import numpy as np

import device.constants as C
from scaleup.c2_budget import GAIN_RANK, gain_correction_bits

J = lambda p: json.loads(Path(p).read_text())
R_ = RP.RESULTS
REG = Path(__file__).resolve().parents[2] / "03_rtl" / "results" / "regression"
u = lambda x, n=2: f"{x*1e6:.{n}f}"          # A -> uA string


def md_table(head, rows):
    return "\n".join(["| " + " | ".join(head) + " |", "|" + "---|" * len(head)] + ["| " + " | ".join(str(c) for c in r) + " |" for r in rows])


def main() -> None:
    prof = {r: list(csv.DictReader(open(RP.FULL_COLUMN / f"group_profile_r{r}.csv"))) for r in C.BL_R_PER_PITCH_SWEEP}
    ts = J(RP.FULL_COLUMN / "ladder_table_size.json")
    acc = J(RP.FULL_COLUMN / "accumulation_test.json"); ctl = J(RP.FULL_COLUMN / "accumulation_negative_controls.json")
    el = J(RP.TRANSIENT / "group_read_energy_latency_summary.json")
    lev = J(RP.MACRO / "row_line_levers.json"); levw = J(RP.MACRO / "row_line_levers_weak_drivers.json")
    droop = J(RP.MACRO / "supply_droop_macro_raw.json"); bud_rail = J(RP.MACRO / "budget_vs_rail.json"); fin = J(RP.MACRO / "budget_final_design.json")
    xt = J(RP.TRANSIENT / "crosstalk_macro_summary.json"); gm = J(RP.MACRO / "row_gain_matrix.json"); gmr = J(RP.MACRO / "row_gain_matrix_with_rails.json")
    arr = J(RP.FULL_ARRAY / "five_macro_dc_raw.json"); atr = J(RP.FULL_ARRAY / "array_transient.json"); area = J(RP.FULL_ARRAY / "area_model.json"); en = J(RP.FULL_ARRAY / "energy_per_inference.json")
    gs = J(RP.READOUT_VARIANTS / "gstar_summary.json"); be = J(RP.READOUT_VARIANTS / "breakeven_summary.json"); c5 = J(RP.COLUMN_SENSING / "column_sensing_table.json")
    val = J(RP.ARRAY_VALIDATION / "mesh_ext_validation_summary.json")
    base = fin["baseline"]; far = base["groups"]["far"]
    cm = c5["cycle_model"]
    L = []
    w = L.append
    w("# Phase 1C report - the full array: 512 x 160, five macros")
    w("")
    w("Tags: **[SIM]** simulated (ngspice, or the mesh solver validated against it), **[MODEL]** analytic in code, **[ASSUM]** assumed (listed in section 14 and swept where it matters), **[CHOICE]** design decision, **[SP]** Stanford-PKU default. "
      "Everything here is regenerated by `python -m scaleup.make_report` from the JSON/CSV files named in each section; commands in section 15.")
    w("")
    w("## 0. The answer")
    w("")
    w(f"- **g stays at 8 - but only because each macro row is driven from BOTH ends, and the margin is thin: {u(base['margin_left_a'])} uA of {u(far['limit_a'])} left ({100*base['margin_frac']:.1f}%), down from 1B's 0.80 uA (6.4%).** "
      f"That is inside the 2-3% Monte-Carlo error of the budget, so g = 8 is **marginal / fragile** (g = 4 is the fallback), as in 1B.")
    w("- **1B's row-line limit was applied at half a macro.** 1B's 'at most 32 columns per row line' was 32 *mesh* columns = 16 differential cells; NeuroHDC's macro row is **32 cells = 64 bitlines** (its 512 x 32-bit SRAM macro stores 4 neurons x 8 bits). "
      f"Re-measured on the true macro with one driver per row the budget **does not close** ({u(next(t['margin_left_a'] for t in lev if t['n_cells']==32 and t['r_drv']==10 and t['r_wl']==0.72 and not t['both_ends']))} uA at R_DRV = 10 ohm: g would fall to 4). "
      f"Drivers at both ends of every row restore it ({u(next(t['margin_left_a'] for t in lev if t['n_cells']==32 and t['r_drv']==10 and t['r_wl']==0.72 and t['both_ends']))} uA before the other 1C terms). Section 4.1.")
    w(f"- **Group profile (C1a):** all 64 groups characterised; level span falls monotonically from {float(prof[0.72][0]['level_span_uA']):.0f} uA (near) to {float(prof[0.72][-1]['level_span_uA']):.0f} uA (far) and the worst step from "
      f"{float(prof[0.72][0]['worst_step_a8_uA']):.1f} to {float(prof[0.72][-1]['worst_step_a8_uA']):.1f} uA (r = 0.72 ohm/pitch; {float(prof[0.5][-1]['worst_step_a8_uA']):.1f} uA at 0.5). The group counts sum to the true 512-row match count in "
      f"{sum(a['reads'] for a in acc)} column reads, with device spread, 0 errors (section 3.2).")
    w(f"- **Ladder table (C1c):** {ts['0.72']['thresholds_total']} thresholds ({ts['0.72']['thresholds_per_group']} per group; {ts['0.72']['thresholds_per_group_half']} with antisymmetry -> {ts['0.72']['thresholds_per_group_half']*64}) = **{ts['0.72']['sizes']['0.1']['half_per_group_range']:,} bits** "
      f"(0.1 uA steps, antisymmetric half; {ts['0.72']['sizes']['0.1']['full_per_group_range']:,} bits full). **New:** the row-line gain is not a per-column constant (1B assumed it was): a per-column scale leaves {100*gm['joint_a_per_column_only_max_resid_frac']:.1f}% error; "
      f"with the rails in a rank-{GAIN_RANK} (column) x (group, a) correction is needed, {gain_correction_bits():,} more bits (section 3.3).")
    w(f"- **Read energy and latency (C1d, C3d).** One macro, a = 8: {el['8']['0']['i_sup_mA']:.1f} mA near group -> {el['8']['63']['i_sup_mA']:.1f} mA far group; array settles to 0.1 uA in {max(float(el['8'][g]['t_settle_ps']['1e-07']) for g in el['8']):.0f} ps worst case. "
      f"Energy of a pulse of length T = V_read x I x (T - {en['tau_s']*1e12:.0f} ps) (+ word line): 1 pJ per ns per macro on average; **the five-macro array is 5x the macro to 0.5% (full-array transient).** "
      f"Per inference with 1E's read pattern: **{en['energy_per_inference_J']['5e-10']['total_J']*1e9:.0f} nJ at a 0.5 ns pulse, {en['energy_per_inference_J']['1e-09']['total_J']*1e9:.0f} nJ at 1 ns, {en['energy_per_inference_J']['1e-08']['total_J']*1e9:.0f} nJ at 10 ns** (array + word line; sense front-end not included). "
      f"The pulse length is set by the sense stage, which 1C does not design: the energy is linear in it. Section 8.")
    w(f"- **Supply droop is real but almost entirely correctable; the data-dependent part is small** - the working premise that droop depends on the total match count does not hold for a differential 2T2R array: every active cell conducts one LRS and one HRS branch whatever it stores, so the total current "
      f"varies by only ~{100*max(r_['isup_std_a']/r_['isup_mean_a'] for r_ in droop if r_['a']==8 and r_['r_rail']==C.RAIL_R_DEFAULT):.1f}% (std/mean) across data, not with the match count. Droop is set by the active-row count a (known digitally -> in the table index). With supply AND ground rails at {C.RAIL_R_DEFAULT} ohm/pitch fed from both ends the data-dependent error is "
      f"{u(far['breakdown']['supply/ground rail (data dependent)'],3)} uA at the far group (0.2 uA worst); **rails 10x weaker (0.072 ohm/pitch) or fed from one end break the budget.** Section 4.2.")
    w(f"- **Crosstalk** (data-dependent, from ngspice transients): 8.8 uA at 40 ps falling to 0.002 uA at 200 ps at the far group (cc = 0.5); it is gone by the time the array has settled. Section 4.3. "
      f"**Five macros switching together do not droop their way out of the budget** (0.17 -> 0.83 mV at the far group, 5x the single macro, data-dependent part 0.03 uA): no staggering needed. Section 5.")
    w(f"- **Area: {area['variants']['baseline: both-end drivers, R_DRV 10']['total_mm2']:.2f} mm^2 for the array plus periphery** (range {area['sensitivity']['low']:.2f}-{area['sensitivity']['high']:.2f} over the layout-density assumptions); the cell array itself is {area['variants']['baseline: both-end drivers, R_DRV 10']['parts_mm2']['cell_array']:.4f} mm^2 "
      f"({100*area['variants']['baseline: both-end drivers, R_DRV 10']['parts_mm2']['cell_array']/area['variants']['baseline: both-end drivers, R_DRV 10']['total_mm2']:.0f}%): **the row drivers (50%) and sense front-ends dominate.** Section 5.3.")
    w("- **Centre tap (C4):** pays only at small sigma_lnG. g = 16 closes to sigma ~ 0.054 at r = 0.5 ohm/pitch but only to ~0.022 at r = 0.72 (1B said 16 up to 0.05 at 0.72: its lumped middle-tap model reused the end-sensed within-group term; measured on the mesh at the true positions it is 2.2x larger). "
      "Segmenting with a sense node in the middle of each segment is better than a centre tap at r = 0.72 (g = 16 to sigma ~ 0.048) at the price of 2-4x the sense front-ends. Nothing helps at sigma >= 0.07. Section 6.")
    w(f"- **Column-sensing decision (C5): sense all 160 columns at once.** It is electrically viable (margin {u(c5['rows'][0]['margin_left_a'])} uA, the same as one macro, at peak {c5['rows'][0]['i_total_near_mA']:.0f} mA) and costs {cm['reads_160']:,.0f} reads / {c5['rows'][0]['cycles']:,.0f} cycles. "
      f"The one-bit-plane mode is *worse* electrically: idle bitlines either float (then charge through their cells and disturb the shared row line: {c5['rows'][-1]['dyn_far_a']*1e6:.1f} uA data-dependent error at 200 ps, closes only from {c5['rows'][-2]['earliest_closing_sampling_ps']} ps) or are clamped (then they draw the full-array current anyway: 8x the energy). Section 7.")
    w("- **Found by testing the 1B/1E pipeline, not asked for:** 62% of 1E's group reads have a = 0 (no row to drive). They cost no array energy, but 1E still spends a cycle on each. Skipping them would cut cycles by "
      f"{100*(en['reads_issued_per_inference']-en['nonzero_reads_per_inference'])/c5['rows'][0]['cycles']:.0f}% (to ~{c5['rows'][0]['cycles']-(en['reads_issued_per_inference']-en['nonzero_reads_per_inference']):,.0f}). Section 8.3.")
    w("")
    w("## 1. What 1C carried forward, and what it re-measured")
    w("")
    w("Carried forward without re-derivation (1B section 12): g = 8, 64 groups, 20 F^2 cell (2T2R 40 F^2, pitch 0.201 um, R_tx 1016 ohm), contiguous groups, a per-group ladder, current-mode sense (R_s = 1 ohm), R_DRV 10 ohm, sigma_lnG 0.10, drift 'moderate' / S1, comparator 1 uA (1 sigma), 20% headroom.")
    w("")
    w("The budget machinery of 1B (`drift.strategies.evaluate` -> `solver.budget.close_budget`) is used unchanged; `scaleup/budget1c.py` only adds terms. **Reproduction check:** feeding 1B's own wire/row terms returns the 1B final margin (0.798 uA, 6.4%, worst group far; "
      "`tests/test_scaleup.py::test_budget_reclosure_reproduces_1b_final_margin`). As a method check the new macro machinery at 1B's geometry (16 cells, one driver, R_DRV 10) gives 0.81 uA (6.5%).")
    w("")
    w("## 2. The solver extension and its validation")
    w("")
    w("`wire.mesh.solve_mesh_ext` extends `solve_mesh` (not a rebuild; the default arguments reproduce it to 1e-14): **macro blocks** (row line broken between macros, each with its own driver), **drive_both_ends**, a **supply rail** feeding every row driver (collapsed exactly over inactive rows, optional second pad = fed from both ends), "
      "a **ground rail** returning the sense nodes (pad per macro), and the supply current per row. It is checked against ngspice with a deck that keeps every physical row and every rail segment (`wire/validate_mesh_ext.py`, `results/array_validation/`):")
    w("")
    w(f"- {val['n']} cases (R = 32 rows, K = 8/16/24 columns in 1-3 blocks, random 2T2R weights with sigma 0.10, 1-16 active rows, rail at either end and both ends, ground pad per macro or single, drivers at one or both ends, wire settings up to 5 ohm/pitch): "
      f"**worst column-current disagreement {val['worst_rel_icol']:.1e}, worst row-supply-current {val['worst_rel_irow']:.1e}**, worst ground-rail voltage {val['worst_abs_vgnd_v']:.0e} V ({val['with_rail']} cases with a rail, {val['with_gnd']} with a ground rail, {val['multi_block']} multi-block).")
    w("- **Transient** (`scaleup/transient.py`, ngspice `.tran`, distributed-RC bitlines to row 512 with neighbour coupling, row-line C, sense C, rail decoupling): the settled currents equal the validated DC mesh to 4e-11 (relative) for a single column and for the 64-bitline macro, "
      "the supply current equals the sum of the sense currents at the end of the pulse, and the pulse energy after settling grows exactly as V I t (`test_transient_steady_state_equals_dc_mesh`). The access transistor is the linear R_tx of 1A (word line asserted before the pulse; "
      "its gate-switching energy is accounted separately from the PTM card: **0.705 fF per 20 F^2 access transistor** at the read bias [SIM], `results/device_characterization/access_transistor_gate_cap.json`). "
      "Not modelled in the transient: BSIM4 channel-charge injection and feedthrough when the word line switches, package/regulator inductance (the supply is an ideal source at the rail pads), the sense stage.")
    w("")
    w("## 3. C1 - the full column")
    w("")
    w("### 3.1 Profile of all 64 groups (C1a)")
    w("")
    w(f"Every group (not a sample) was solved on the mesh with 40 fit and 40 held-out random (active subset, weights) patterns per (a, m) plus the two extremal match placements, for r = 0.5 and 0.72 ohm/pitch (`results/full_column/group_tables_r*.json`, `group_profile_r*.csv`, Figure 7). Selected groups (r = 0.72):")
    w("")
    sel = (0, 8, 16, 24, 32, 40, 48, 56, 63)
    w(md_table(["group", "first row (pitches from sense)", "level span (uA)", "worst step a=8 (uA)", "step vs near", "within-group half-range (uA)", "held-out deviation (uA)"],
               [[int(prof[0.72][g]["group"]), prof[0.72][g]["first_row_pos"], prof[0.72][g]["level_span_uA"], prof[0.72][g]["worst_step_a8_uA"], prof[0.72][g]["step_vs_near"], prof[0.72][g]["within_group_halfrange_uA"], prof[0.72][g]["heldout_dev_uA"]] for g in sel]))
    w("")
    for r in C.BL_R_PER_PITCH_SWEEP:
        o = ts[str(r)]
        w(f"- r = {r}: span {o['span_near_uA']:.0f} -> {o['span_far_uA']:.0f} uA ({o['span_ratio_near_over_far']:.2f}x), worst step {o['step_near_uA']:.1f} -> {o['step_far_uA']:.1f} uA (**{o['step_ratio_near_over_far']:.2f}x**; 1B: 2.7-3.6x). "
          f"**Monotone in distance: span {o['monotone_span']}, step at a = 8 {o['monotone_step_a8']}, worst step over every a {o['monotone_step_any_a']}.**")
    w(f"- Within-group half-range (the uncorrectable in-group wire term) falls from {prof[0.72][0]['within_group_halfrange_uA']} uA (near) to {prof[0.72][-1]['within_group_halfrange_uA']} uA (far), and the far value reproduces 1B's mesh term (0.49 uA). Held-out patterns deviate from the table centre by no more than "
      f"{ts['0.72']['max_heldout_dev_uA']:.2f} uA anywhere: the fitted table generalises.")
    w("")
    w("### 3.2 Accumulation across groups (C1b)")
    w("")
    n8 = sum(a['reads'] for a in acc if a['g'] == 8); d8 = sum(a['group_decisions'] for a in acc if a['g'] == 8)
    w(f"One trial = one column read: random 512-bit weights, random activations; per group the active rows are solved on the mesh (device spread sigma 0.10 or none), the count is decided from that group's own table row a, the group counts are added and compared with the integer Python model sum(x & w). "
      f"Activity densities 0.25, **0.51 (the measured mean active-address density)**, 0.75 and 1.0 (worst).")
    w("")
    w(md_table(["g (partition)", "reads", "group decisions", "sum errors", "wrong group decisions", "smallest decision margin (fraction of half-step), sigma 0.10"],
               [[f"{g} ({'ragged: ' + str(512 % g) + ' rows in the last group' if 512 % g else 'even'})", sum(a['reads'] for a in acc if a['g'] == g), sum(a['group_decisions'] for a in acc if a['g'] == g), sum(a['sum_errors'] for a in acc if a['g'] == g),
                 sum(a['wrong_group_decisions'] for a in acc if a['g'] == g), f"{min(a['min_margin_frac_of_halfstep'] for a in acc if a['g']==g and a['sigma']==0.1):.2f}"] for g in (8, 5, 6, 7)]))
    w("")
    w(f"**0 errors in {sum(a['reads'] for a in acc)} column reads.** The smallest margin at g = 8 is {min(a['min_margin_frac_of_halfstep'] for a in acc if a['g']==8 and a['sigma']==0.1):.2f} of the half-step over {d8:,} decisions (1B's 5-sigma spread term is 0.53 of the far group's half-step: 8.2 of 15.5 uA). "
      "Negative controls show the test would catch a sequencer fault (`accumulation_negative_controls.json`):")
    w("")
    w(md_table(["fault injected", "reads", "column sums wrong", "group decisions wrong"],
               [[{"table": "table of the group k positions away", "a": "active count a off by", "shift": "activation vector shifted by one row"}[c["kind"]] + f" ({c['value']}{'; = one group the other way' if c['kind']=='table' and c['value']==63 else ''})", c["reads"], c["sum_errors"],
                 ("n/a (each decision is right for the data it saw; the sum is wrong)" if c["kind"] == "shift" else f"{c['wrong_decisions']} / {c['decisions']}")] for c in ctl]))
    w("")
    w("A table indexed one group off already produces wrong counts (~1% of decisions): the sequencer must index the right group's table, but exactness is not delicate beyond that; a miscounted a or a row-misaligned activation is caught in essentially every read.")
    w("")
    w("### 3.3 The per-group ladder table (C1c)")
    w("")
    o = ts["0.72"]
    w(f"- **Size:** per group, a = 1..8 and thresholds between m = k and k+1: {o['thresholds_per_group']} thresholds; x 64 groups = **{o['thresholds_total']}**. Levels are antisymmetric per group (I_diff(a, m) = -I_diff(a, a-m)) to within **{o['antisym_dev_max_uA']:.2f} uA worst over all groups "
      f"({o['antisym_dev_far_uA']:.3f} uA at the far group)**, so half can be stored: {o['thresholds_per_group_half']} per group = {o['thresholds_per_group_half']*64}, error {o['antisym_dev_far_uA']/2:.3f} uA at the far group (a budget term, section 4.4).")
    w("")
    rows = [[q, o["sizes"][q]["bits_per_threshold_worst_group"], f"{o['sizes'][q]['full_per_group_range']:,}", f"{o['sizes'][q]['half_per_group_range']:,}", f"{float(q)/2:.3f}"] for q in ("0.02", "0.05", "0.1", "0.2", "0.5", "1.0")]
    w(md_table(["threshold step (uA)", "bits / threshold (worst group)", "full table (bits, per-group range)", "half table (bits)", "quantisation error +/- (uA, a budget term)"], rows))
    w("")
    w(f"  The table is shared by all 160 columns (every column reads the same group and the same a). At 0.1 uA steps it is **{o['sizes']['0.1']['half_per_group_range']:,} bits** (half) - 20% of the 81,920 weight bits. A low-rank factorisation of the thresholds is not viable "
      f"(rank 2 leaves {o['factorised']['2']['max_resid_uA']:.1f} uA).")
    w("- **The row-line gain correction that 1B called 'a per-column scale' (new):** the row-line IR makes the signal of column c in group G a fraction s(c, G) of its single-column value; s depends on G as well as c. Measured on a 17 x 22 grid of (cell, group) at full scale: "
      f"s ranges {gm['min']:.3f}-{gm['max']:.3f}; **a per-column constant leaves up to {100*gm['per_column_only_max_resid_frac']:.1f}% error** (= {gm['per_column_only_max_resid_frac']*float(prof[0.72][-1]['level_span_uA'])/2:.1f} uA at the far group's top level, {gm['per_column_only_max_resid_frac']*float(prof[0.72][-1]['level_span_uA'])/2/0.8:.0f} x the 0.8 uA left in the budget); "
      f"rank 1 leaves {100*gm['rank1_max_resid_frac']:.1f}%, **rank 2 {100*gm['rank2_max_resid_frac']:.2f}%** with ideal rails. With the supply/ground rails the gain also depends on a (more active rows -> more rail current), and the best joint (column) x (group, a) fit is rank 3: "
      f"{100*gmr['joint_a_rank2_max_resid_frac']:.2f}% at rank 2, **{100*gmr['joint_a_rank3_max_resid_frac']:.2f}% at rank 3** ({gmr['joint_a_rank3_max_resid_frac']*float(prof[0.72][-1]['level_span_uA'])/2:.2f} uA at the far group, entered in the budget). "
      f"Storage of the rank-{GAIN_RANK} factors with 12-bit numbers: **{gain_correction_bits():,} bits** (3 x (32 + 512) numbers). Total correction state {o['sizes']['0.1']['half_per_group_range']+gain_correction_bits():,} bits.")
    w("")
    w("### 3.4 Read energy and latency per group read (C1d)")
    w("")
    w("`results/transient/group_read_energy_latency_macro.json` (384 ngspice transients: all 64 groups x a = 8 and a = 4 x 3 weight patterns; one macro = 512 x 32 cells = 64 bitlines, drivers at both ends, ideal supply). Settling time = the last instant at which the differential current of ANY of the 32 cell columns is more than eps from its final value. Energy = integral of V_pad x I_supply from the start of the 20 ps rise.")
    w("")
    rows = []
    for a in ("8", "4"):
        i = [el[a][str(g)]["i_sup_mA"] for g in range(64)]
        for nm, g in (("near (group 0)", "0"), ("middle (group 32)", "32"), ("far (group 63)", "63")):
            e = el[a][g]["energy_pJ"]
            rows.append([a, nm, f"{el[a][g]['i_sup_mA']:.2f}", f"{el[a][g]['t_settle_ps']['1e-07']:.0f}", f"{e['5e-10']:.3f}", f"{e['1e-09']:.3f}", f"{e['1e-08']:.2f}"])
        e_mean = {T: np.mean([el[a][str(g)]["energy_pJ"][T] for g in range(64)]) for T in ("5e-10", "1e-09", "1e-08")}
        rows.append([a, "**mean over the 64 groups**", f"{np.mean(i):.2f}", f"{np.mean([el[a][str(g)]['t_settle_ps']['1e-07'] for g in range(64)]):.0f}", f"{e_mean['5e-10']:.3f}", f"{e_mean['1e-09']:.3f}", f"{e_mean['1e-08']:.2f}"])
    w(md_table(["active rows a", "group", "supply current (mA)", "settle to 0.1 uA (ps)", "E, 0.5 ns pulse (pJ)", "E, 1 ns (pJ)", "E, 10 ns (pJ)"], rows))
    w("")
    w(f"Far groups draw less (compressed by their bitline). The current is proportional to a (13.8 vs 6.9 mA at the near group). Worst array settling over all groups and patterns: {max(max(r_['t_settle_ps'][e] for g_ in range(64) for r_ in [el[a_][str(g_)]]) for a_ in ('8','4') for e in ['1e-07']):.0f} ps to 0.1 uA "
      f"({max(max(el[a_][str(g_)]['t_settle_ps']['5e-08'] for g_ in range(64)) for a_ in ('8','4')):.0f} ps to 0.05 uA). **A macro group read of a = 8 costs 0.49 pJ per 0.5 ns of pulse on average (energy ~ 1 pJ per ns per macro); the word line adds "
      f"{en['e_wl_per_active_row_array_J']/5*1e15:.0f} fJ per active row per macro ({en['e_wl_per_active_row_array_J']*1e15:.0f} fJ for the array).** Full array: five macros read together in one transient (`results/full_array/array_transient.json`) give "
      + "; ".join(f"G = {r_['G']}, a = {r_['a']}: {r_['i_sup_A']*1e3:.1f} mA, {r_['energy_J']['5e-10']*1e12:.2f} pJ per 0.5 ns, settle {r_['t_settle_s']['1e-07']*1e12:.0f} ps" for r_ in atr[:2]) + " - five times the single macro to 0.5%, and the same latency.")
    w("")
    w("## 4. C2 - one macro, 512 x 32 cells")
    w("")
    w("### 4.1 The row line of the true macro")
    w("")
    w("1B measured the row line on 32 mesh columns (16 cells). The true macro is 64 mesh columns. Re-measured with the 1B method (fixed own pattern, random weights in every other column; worst of the first / middle / last cell; far and near group) and re-closed through the 1B budget (`results/macro_512x32/row_line_levers.json`, `row_line_levers_weak_drivers.json`, Figure 8):")
    w("")
    rl = [t for t in lev if t["n_cells"] == 32] + [dict(t, n_cells=32, both_ends=True) for t in levw if t["r_drv"] > 10]
    def lv(rd, rwl, both): return next((t for t in rl if t["r_drv"] == rd and t["r_wl"] == rwl and t["both_ends"] == both), None)
    rows = []
    for rd in (1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 50.0):
        r1 = lv(rd, 0.72, False); r2 = lv(rd, 0.72, True); r3 = lv(rd, 0.36, True)
        rows.append([rd, f"{u(r1['margin_left_a'])} ({r1['gain_far']:.2f})" if r1 else "-", f"{u(r2['margin_left_a'])} ({r2['gain_far']:.2f})" if r2 else "-", f"{u(r3['margin_left_a'])} ({r3['gain_far']:.2f})" if r3 else "-"])
    w(md_table(["R_DRV (ohm)", "one driver per row: margin uA (far-group gain)", "drivers at both ends: margin (gain)", "both ends, row line 2x better (0.36 ohm/pitch)"], rows))
    w("")
    t16 = next(t for t in lev if t["n_cells"] == 16)
    w(f"- Method check at 1B's geometry (16 cells, one driver, R_DRV 10): margin {u(t16['margin_left_a'])} uA, far gain {t16['gain_far']:.3f} (1B: 0.80 uA, 0.908).")
    w("- With one driver at the row end the last/middle column of the 32-cell macro loses 20-25% of its signal and the budget fails at R_DRV >= 5 ohm; a 1-2 ohm driver closes it barely (0.1-0.15 uA) at an enormous driver area. **Drivers at both ends** (equivalent electrically to two 16-cell halves) close it with R_DRV up to ~30 ohm. "
      "**1B's requirement 'R_DRV <= 10 ohm' should read: drivers at both ends of a 32-cell row, R_DRV <= 10-20 ohm each.** The driver area consequence is in section 5.3.")
    w("")
    w("### 4.2 Supply droop and ground rise (C2a)")
    w("")
    w("Model: a vertical supply rail feeds every row driver (pad at the sense end, and optionally a second pad at the far end), a horizontal ground rail returns the 64 sense nodes (pad at the macro's first column), resistance per cell pitch swept 0.72 (signal metal) to 0.00072 ohm/pitch (thick top-metal strap). "
      "Baseline macro (drivers at both ends, R_DRV 10, row line 0.72), a = 8, groups 0, 8, ..., 63, victim = first / middle / last cell, 8 own x 40 other draws (`supply_droop_macro_raw.json`, Figure 9 left). "
      "X0 = victim I_diff with ideal rails (row-line IR only), X1 = with rails; what varies with the other columns' data for a fixed own pattern is the uncorrectable part:")
    w("")
    agg = defaultdict(list)
    for r_ in droop:
        if r_["a"] == 8:
            agg[(r_["r_rail"], r_["feed_both"])].append(r_)
    rows = []
    for rho in (0.00072, 0.0072, 0.072, 0.72):
        for fb in (True, False):
            rs = agg.get((rho, fb))
            if not rs:
                continue
            b = next(x for x in bud_rail if x["r_rail"] == rho and x["feed_both"] == fb)
            rows.append([rho, "both ends" if fb else "one end", f"{max(r_['droop_mean_v'] for r_ in rs)*1e3:.1f}", f"{max(r_['gnd_max_v'] for r_ in rs)*1e3:.1f}", f"{max(r_['rail_mean_shift_a'] for r_ in rs)*1e6:.1f}", f"{max(r_['rail_inc_std_a'] for r_ in rs)*1e6:.3f}", f"{max(r_['rail_inc_maxdev_a'] for r_ in rs)*1e6:.3f}",
                         f"{min(r_['gain_total'] for r_ in rs):.2f}", f"{u(b['margin_left_a'])} ({'closes' if b['closes'] else 'FAILS'})"])
    w(md_table(["rail r (ohm/pitch)", "supply fed from", "mean supply droop (mV, worst group)", "ground rise (mV)", "mean level shift (uA, correctable)", "data-dependent 1 sigma (uA)", "data-dependent max deviation (uA)", "min gain", "budget margin (uA)"], rows))
    w("")
    iv = [r_["isup_std_a"] / r_["isup_mean_a"] for r_ in droop if r_["a"] == 8 and r_["r_rail"] == C.RAIL_R_DEFAULT]
    w(f"- **Is droop data-dependent?** Barely. At the baseline rails the data-dependent increment is at most {max(r_['rail_inc_maxdev_a'] for r_ in agg[(C.RAIL_R_DEFAULT, True)])*1e6:.2f} uA (max over groups and victims) against a mean level shift of up to {max(r_['rail_mean_shift_a'] for r_ in agg[(C.RAIL_R_DEFAULT, True)])*1e6:.0f} uA. "
      f"The total supply current varies by only {100*max(iv):.1f}% (std/mean) over random data because every active 2T2R cell conducts one LRS and one HRS branch regardless of the stored bit: the droop depends on **how many rows are active (a)**, which the digital side knows and which already indexes the table, "
      "and weakly on compression. The 'depends on the match count across the 32 columns' picture holds for a single-ended array, not for this one.")
    w("- **What the rails must be:** the *mean* droop (up to 8 mV = 8% of V_read at 0.0072 ohm/pitch) is not an error if it is the same every read - it is baked into the table through a - but it eats signal (the gain falls with it) and grows the data-dependent part. "
      f"Requirement from the budget: **supply and ground rails <= {C.RAIL_R_DEFAULT} ohm/pitch fed from both ends, or <= 0.00072 from one end**. At 0.2 um pitch and a top-metal sheet resistance of 0.02 ohm/sq (assumed) 0.0072 ohm/pitch is a {0.02*C.PITCH_UM_1C/C.RAIL_R_DEFAULT:.2f} um-wide strap: negligible area.")
    w("")
    w("### 4.3 Crosstalk between adjacent bitlines (C2b)")
    w("")
    w("`scaleup/run_crosstalk.py`: one macro, 64 bitlines with distributed R and C along the full 512-pitch length (C = 0.2 fF/pitch total [ASSUM, 1A], a fraction cc of it coupled to the two neighbours), victim = middle cell, 12 patterns of all other cells (random and two adversarial: every + device LRS / every one HRS), "
      "own pattern fixed, 20 ps rise. The cc = 0 run has the same total capacitance, all to ground: pure RC settling. Data-dependent error = spread over the patterns of (I_diff(t) - I_diff(final)) (Figure 9 right, `crosstalk_macro_summary.json`):")
    w("")
    ts_ps = xt["t_s_ps"]
    rows = []
    for G, nm in (("63", "far"), ("0", "near")):
        for cc in ("0.0", "0.25", "0.5", "0.75"):
            e = xt["groups"][G][cc]["spread_a"]
            rows.append([nm, cc] + [f"{e[ts_ps.index(t)]*1e6:.3f}" for t in (60, 100, 130, 160, 200, 300)])
    w(md_table(["group", "cc"] + [f"{t} ps" for t in (60, 100, 130, 160, 200, 300)], rows))
    w("")
    w("(uA; 'cc 0' = settling alone has no data dependence). **Crosstalk depends on the neighbours' data and is largest in the far group** (its bitline is longest: 8.8 uA at 40 ps, cc 0.5), but it decays with a time constant of ~20 ps: the data-dependent error is 0.07-0.22 uA at 130 ps, 0.01-0.05 at 160 ps and below 0.01 uA from 200 ps. "
      "**No sampling-time penalty beyond ~200 ps; sampling at 130 ps costs 0.1-0.2 uA of margin.**")
    w("")
    w("### 4.4 The budget re-closed (C2c)")
    w("")
    w(f"Baseline 1C design: drivers at both ends (R_DRV 10, row line 0.72), supply and ground rails {C.RAIL_R_DEFAULT} ohm/pitch fed from both ends, sampled at 200 ps (cc 0.5), ladder thresholds in 0.1 uA steps, antisymmetric half-table, rank-{GAIN_RANK} gain correction. Far group (worst step {u(far['delta_a'])} uA, limit {u(far['limit_a'])} uA):")
    w("")
    w(md_table(["term", "kind", "uA"] , [[k, ("random (5 sigma, quadrature)" if k in ("device spread", "absolute signal (comparator noise)", "row-driver IR") else "deterministic (linear)"), f"{v*1e6:.3f}"] for k, v in far["breakdown"].items()]))
    w("")
    w(f"Total error {u(far['total_a'])} uA; **margin left {u(base['margin_left_a'])} uA = {100*base['margin_frac']:.1f}% of the limit (1B: 0.80 uA, 6.4%).** The new terms add {u(sum(far['breakdown'][k] for k in far['breakdown'] if k in ('supply/ground rail (data dependent)', 'settling + crosstalk at sampling time', 'ladder threshold quantisation', 'antisymmetric (half) table storage', f'row-gain correction residual (rank {GAIN_RANK})')))} uA; "
      f"the row-driver term fell (1.83 -> {u(far['breakdown']['row-driver IR'])} uA) while the far-group gain with the rails is {base['rows']['far']['gain']:.3f} (1B: 0.908) and the near group's {base['rows']['near']['gain']:.3f} (1B: 0.824). **Whenever a term is measured, the remaining margin is stated: 0.80 -> 0.69 (both-end rows + rails + dynamics) -> 0.48 uA after the rank-3 gain residual.** "
      "Sensitivities (same budget):")
    w("")
    w(md_table(["variation", "margin (uA)", "closes"],
               [[f"sampling at {x['t_s_ps']} ps, cc {x['cc']}", u(x["margin_left_a"]), x["closes"]] for x in fin["vs_sampling_time"] if x["t_s_ps"] in (100, 130, 160, 200)] +
               [[f"R_DRV {x['r_drv']:.0f} ohm (both ends)", u(x["margin_left_a"]), x["closes"]] for x in fin["vs_r_drv"]] +
               [[f"rails {x['rho']} ohm/pitch, fed from {'both ends' if x['feed_both'] else 'one end'}", u(x["margin_left_a"]), x["closes"]] for x in fin["vs_rail"]]))
    w("")
    w("**Outcome: g = 8 survives with 0.48 uA (3.9%); if any of these - both-end rows, 0.0072 ohm/pitch rails fed both ends, sampling after ~130 ps, a rank-3 gain correction - is dropped, g falls to 4.** The budget is within its Monte-Carlo error of zero, so the honest label is *marginal*.")
    w("")
    w("## 5. C3 - five macros, the full 512 x 160")
    w("")
    w("### 5.1 Supply across macros (C3a, C3b)")
    w("")
    w("160 cells = 81,920 bits as five macros, each with its own row drivers (both ends) and its own sense periphery / ground pad; the supply rail of a row is shared by the drivers of all five macros. K = 320 bitlines on the mesh (`results/full_array/five_macro_dc_raw.json`). The first m macros sensing (a = 8; group 63 = far, 0 = near; rails 0.0072, fed from both ends):")
    w("")
    ag = defaultdict(list)
    for r_ in arr:
        ag[(r_["r_rail"], r_["feed_both"], r_["G"], r_["mode"])].append(r_)
    rows = []
    for m in range(1, 6):
        for G, nm in ((63, "far"), (0, "near")):
            rs = ag[(0.0072, True, G, f"macros={m}")]
            rows.append([f"{32*m} cells ({m} macro{'s' if m > 1 else ''})", nm, f"{np.mean([x['isup_mean_a'] for x in rs])*1e3:.1f}", f"{max(x['droop_mean_v'] for x in rs)*1e3:.2f}", f"{max(x['gnd_max_v'] for x in rs)*1e3:.2f}", f"{max(x['rail_inc_maxdev_a'] for x in rs)*1e6:.3f}", f"{min(x['gain_total'] for x in rs):.3f}"])
    w(md_table(["sensing", "group", "supply current (mA)", "mean droop (mV)", "ground rise (mV)", "data-dependent (uA, max dev)", "min gain"], rows))
    w("")
    w("- **Five macros do droop 5x more than one in absolute terms** (0.17 -> 0.83 mV far, 0.31 -> 1.51 mV near; 37 -> 69 mA peak), because the rail is shared; the ground rises do not add (each macro has its own pad). It makes **no difference to the budget** (data-dependent part <= 0.05 uA, gain 0.892 -> 0.886): "
      "**the macros need not be staggered** provided the strap is 0.0072 ohm/pitch or better and fed from both ends. Fed from one end the five-macro array collapses (57 mV droop, gain 0.39 at the far group at 0.0072; at 0.00072 it is 12 mV): the two-end feed is a requirement, not a refinement.")
    w("- The mean level shift depends on how many macros share the rail (the measured shifts, 2.05 vs 2.13 uA far and 12 vs 15 uA near for 1 vs 5 macros, are within the sampling noise of these estimates, about +/-3 uA near): the thresholds are calibrated for the sensing configuration actually used.")
    w("- **Decoupling and supply dynamics** (`scaleup/run_supply_dynamics.py`, `supply_dynamics_raw.json`): the DC study above assumes the rail pads sit on an ideal supply. With a pre-charged decoupling C_dec, a switched row driver (20 ps) and an assumed pad network "
      "(regulator + package: R_pad 0.5 ohm, L_pad 100 pH [ASSUM]) behind the baseline rails, one macro, a = 8:")
    w("")
    sd = J(RP.TRANSIENT / "supply_dynamics_raw.json"); tsd = np.array(sd["t_s"]) * 1e12; i200 = int(np.argmin(abs(tsd - 200)))
    rows = []
    for G, nm in ((63, "far"), (0, "near")):
        for cd in (0.0, 10e-12, 100e-12, 1e-9):
            rr = [r for r in sd["runs"] if r["G"] == G and r["cdec_total_F"] == cd]
            e = np.array([r["err_a"] for r in rr])
            rows.append([nm, f"{cd*1e12:.0f}", f"{min(r['v_rail_min_V'] for r in rr)*1e3:.0f}", f"{np.mean([r['v_rail_final_V'] for r in rr])*1e3:.0f}", f"{max(r['settle_s'] for r in rr)*1e12:.0f}",
                         f"{np.abs(e).max(0)[i200]*1e6:.2f}", f"{np.abs(e - e.mean(0)).max(0)[i200]*1e6:.3f}"])
    w(md_table(["group", "C_dec (pF, total)", "rail minimum (mV)", "rail final (mV)", "settle to 0.1 uA (ps)", "common-level error at 200 ps (uA, magnitude)", "data-dependent spread at 200 ps (uA)"], rows))
    w("")
    w("  **The supply dynamics add no data dependence (spread <= 0.23 uA in every case, 0.01-0.07 uA near) - but they move the usable sampling time.** With no decoupling the rail dips (L di/dt, 10-17 mV below its final level) and recovers within the array's own ~120 ps; "
      "adding decoupling to this lightly damped network (Q ~ 6 at 10 pF) makes it ring, and the common level then needs 0.8-1.6 ns to settle (8-40 uA of common-level error at 100-300 ps in the near group). The error is the same every read (a common level set by G and a, so calibratable at a fixed sampling time) "
      "but that level now depends on the PDN's damping: **the sampling time (hence the pulse length and the energy of section 8) is a PDN design output, not an array property**; the array alone needs ~0.15 ns.")
    w("- **Decoupling charge if the regulator cannot follow the step** (upper bound, no regulator model): Q = I x T (34 pC for 69 mA x 0.5 ns) must come from on-chip capacitance, C >= Q/dV: for dV = 5 mV "
      f"{area['decap']['dv=5mV,T=0.5ns']:.2f} mm^2 at 10 fF/um^2, for dV = 50 mV (half the read voltage) {area['decap']['dv=50mV,T=0.5ns']:.3f} mm^2 - comparable to or larger than the rest of the array. "
      "This is the biggest unmodelled risk of the very short pulse that the energy numbers assume (section 14).")
    w("")
    w("### 5.2 Array energy, latency (C3d)")
    w("")
    w("Latency: the array itself needs ~130-160 ps (settle to 0.1 uA / crosstalk below 0.1 uA); sampling at 200 ps loses nothing. Energy: section 8. The full-array transient (320 bitlines, `array_transient.json`) confirms energy = 5 x macro and the same settling.")
    w("")
    w("### 5.3 Area (C3c)")
    w("")
    ab = area["variants"]["baseline: both-end drivers, R_DRV 10"]
    extra_fe = lambda k: k * ab["parts_mm2"]["sense_front_ends"] * (1 + 0.20)
    from scaleup.area import area as area_fn
    shares = {nm: area_fn(level=lv) for lv, nm in enumerate(("low", "mid", "high"))}
    drv_share = {nm: a_["parts_um2"]["row_drivers"] / sum(a_["parts_um2"].values()) for nm, a_ in shares.items()}
    arr_share = {nm: a_["parts_um2"]["cell_array"] / sum(a_["parts_um2"].values()) for nm, a_ in shares.items()}
    w(f"No layout exists; each periphery size is an assumption (section 14) with a low / mid / high range, and the point of the table is the **ranking** (`scaleup/area.py`, `area_model.json`, Figure 12). Cell array = 512 x 160 x 40 F^2 (F = 45 nm) = {ab['parts_mm2']['cell_array']:.4f} mm^2 [MODEL]. Driver width W = 548.7 ohm.um / R_DRV [SIM: 1A R_tx x W].")
    w("")
    w(md_table(["variant", "total (mm^2)", "cell array", "row drivers", "sense front-ends + DACs", "ladder + gain storage", "word-line bufs + decoder", "overhead 20%"],
               [[nm, f"{v['total_mm2']:.3f}", f"{v['parts_mm2']['cell_array']:.4f}", f"{v['parts_mm2']['row_drivers']:.4f}", f"{v['parts_mm2']['sense_front_ends']+v['parts_mm2']['reference_dacs']:.4f}", f"{v['parts_mm2']['ladder_and_gain_storage']:.4f}",
                 f"{v['parts_mm2']['wordline_buffers']+v['parts_mm2']['row_decoder']:.4f}", f"{v['parts_mm2']['overhead_20pct']:.4f}"] for nm, v in area["variants"].items()]))
    w("")
    w(f"- Density sensitivity of the baseline total: low / mid / high = {area['sensitivity']['low']:.3f} / {area['sensitivity']['mid']:.3f} / {area['sensitivity']['high']:.3f} mm^2. **The cell array is {100*arr_share['low']:.0f}% / {100*arr_share['mid']:.0f}% / {100*arr_share['high']:.0f}% of the total at the low / mid / high density assumptions and the row drivers {100*drv_share['low']:.0f}% / {100*drv_share['mid']:.0f}% / {100*drv_share['high']:.0f}%: periphery dominates under every assumption.** The row drivers (5,120 of them, 55 um wide each at 10 ohm) are the largest part and the single biggest lever: "
      "R_DRV 20 ohm both ends saves {100*(1-area['variants']['both-end R_DRV 20']['total_mm2']/ab['total_mm2']):.0f}% of the total at a cost of {u(fin['vs_r_drv'][0]['margin_left_a']-fin['vs_r_drv'][1]['margin_left_a'])} uA of margin (section 4.4); a single 2 ohm driver per row (the only single-ended option that closes) multiplies the total by {area['variants']['single-end driver R_DRV 2 (budget just closes)']['total_mm2']/ab['total_mm2']:.2f}.")
    w("- **NeuroHDC comparison basis** (their Table III, NeuroHDC-small, DVS-Gesture, 20 neurons, scaled by them to 45 nm): **0.399 mm^2** (whole accelerator, 130 nm: 2.494 mm^2), **3.01 uJ per inference** (130 nm: 41.61 uJ), 100 MHz clock, latency 1.8 ms at 130 nm. "
      f"Their weight memory is the same 5 x (512 x 32) organisation (10.24 kB). Our {ab['total_mm2']:.2f} mm^2 is the weight memory plus its analog periphery only; the 1E digital logic ({'9,352'} flip-flops generic) and the class-hypervector memory add to it in Phase 5, and their figure cannot be split into SRAM and logic from the paper. "
      f"A like-for-like latency comparison needs the same event count: ours is {cm['runs']['dvs_seed0_g8_c160']['events']:,.0f} events per sample (1.14 cycles/event); 1.8 ms at 100 MHz would be 180,000 cycles, i.e. their samples are not the same length.")
    w("")
    w("## 6. C4 - centre tap and segmented columns")
    w("")
    w("Method (`scaleup/variants.py`, `run_variants.py`, `run_variants_breakeven.py`): for each variant the physical distance of every row to the sense node that reads it is defined; the far and near groups are located; the within-group wire error and the 64-bitline row-line gain/spread are measured **on the mesh at those exact positions**; "
      "the 1B budget (S1, drift 'moderate', 20 F^2, R_s 1 ohm, 0.8 headroom unchanged) is evaluated at both groups; g* = largest g in {4, 8, 16, 32} that closes. Variants: end (baseline), centre (node between rows 255 and 256), segN_end / segN_mid (N sense nodes per column at the end / middle of each segment).")
    w("")
    sig = gs["sigmas"]
    w(md_table(["variant", "bitline r"] + [f"sigma {s}" for s in sig], [[k.split("|")[0], k.split("|")[1]] + v for k, v in gs["gstar"].items()]))
    w("")
    w("(g* by sigma_lnG.) **Margins at g = 16** (% of the limit; negative = does not close) and the sigma at which g = 16 stops closing (interpolated), Figure 11:")
    w("")
    w(md_table(["variant", "r", "sigma at which g = 16 stops closing"] + [f"{s}" for s in (0.01, 0.03, 0.05, 0.07)],
               [[k.split("|")[0], k.split("|")[1], ("never (fails even at 0.01)" if v["sigma_break_even_g16"] == 0.0 else f"{v['sigma_break_even_g16']:.3f}")] + [f"{100*dict(v['margins'])[s]:+.0f}%" for s in (0.01, 0.03, 0.05, 0.07)] for k, v in be.items()]))
    w("")
    w("- **Centre tap**: far distance 256 instead of 512. At r = 0.72 g = 16 closes only up to sigma ~ 0.022 (1B: 0.05); at r = 0.5 up to ~0.054. 1B's lumped 'middle' estimate reused the end-sensed within-group wire term (1.8 uA at g = 16); at the actual centre-tap far group (positions 241-256) the bitline carries more current and the term is 4.0 uA. "
      "Cost: no extra sense circuits (one node per column, in the middle), but the sense strip sits inside the array (two bitline arms per front-end, symmetric layout), and its input sees the idle arm's 51 fF.")
    w(f"- **Segmented, node in the middle of each segment** (seg2_mid: 2 nodes per column, 128 pitches to the farthest row): g = 16 closes up to sigma ~ 0.048 at r = 0.72 and does not improve with more segments (seg4/seg8 ~ 0.049): the near-group within-group wire term then binds. Cost: a second set of sense front-ends = +{extra_fe(1):.3f} mm^2 (+{100*extra_fe(1)/ab['total_mm2']:.0f}%) at 2 segments, +{extra_fe(3):.3f} mm^2 at 4; "
      "end-sensed segments (seg4_end) give the same g* with twice the front-ends of seg2_mid.")
    w("- **Where it pays off:** sigma_lnG <= ~0.05 (seg2_mid; centre tap only at <= 0.022 at r = 0.72 or <= 0.054 at r = 0.5). **At sigma >= 0.07 neither buys anything; at 0.10 nothing does.** 1B's finding that tight programming helps only below ~0.10 stands, and the layout lever helps only below ~0.05.")
    w(f"- **What a factor 2 in g is worth** (correcting the premise): the DC array energy is Sum(active rows) x V x I_row x T and does not depend on g; what g changes is the *number of reads*: {cm['reads_160']:,.0f} (g = 8) -> {cm['reads_160']/2:,.0f} (g = 16), i.e. cycles {c5['rows'][0]['cycles']:,.0f} -> {c5['rows'][0]['cycles']-cm['reads_160']/2:,.0f} ({100*cm['reads_160']/2/c5['rows'][0]['cycles']:.1f}% fewer) "
      "and every per-read fixed cost (comparators, reference DACs, word-line toggling). With a per-read fixed energy E_f the saving is 26,795 x E_f per inference (27 nJ for E_f = 1 pJ). **Recommendation:** stay at g = 8 with an end-sensed column; adopt seg2_mid only if sigma_lnG <= 0.04 is demonstrated (1D) *and* the sense front-end energy per read exceeds a few pJ - otherwise the extra front-end area is not repaid.")
    w("")
    w("## 7. C5 - the column-sensing decision")
    w("")
    w(f"Digital cost (1E, g = 8, measured): 160 columns at once {cm['reads_160']:,.0f} reads / {c5['rows'][0]['cycles']:,.0f} cycles; 20 at a time 428,717 / 837,745. The 1E cycle counts fit **cycles = {cm['c0']:,.0f} + group reads** to within {cm['c0_spread']:.0f} cycles over all seven 1E runs (g = 4..64 at 160 columns, 20 columns at g = 8 and 64): "
      "one cycle per group read on top of ingest. So for any width W (passes = ceil(160/W)) the cycle count follows. Electrical side: the five-macro DC study, plus crosstalk transients for the bit-plane mode (`column_sensing_table.json`, `crosstalk_bitplane_raw.json`).")
    w("")
    rows = []
    for r_ in c5["rows"]:
        if r_["rho"] != C.RAIL_R_DEFAULT:
            continue
        rows.append([r_["W"], r_["mode"], r_["passes"], f"{r_['reads']:,.0f}", f"{r_['cycles']:,.0f}", f"{r_['i_total_near_mA']:.1f}", f"{r_['dyn_far_a']*1e6:.3f}", f"{u(r_['margin_left_a'])} ({100*r_['margin_frac']:+.1f}%)", "yes" if r_["closes"] else f"NO (closes from {r_['earliest_closing_sampling_ps']} ps)"])
    w(md_table(["columns sensed at once", "mode", "passes", "group reads / inference", "cycles / inference", "peak current, near group (mA)", "dynamic error at 200 ps (uA)", "budget margin", "closes at 200 ps"], rows))
    w("")
    w("- **160 at once is electrically viable and has the lowest cycle count**; every contiguous-macro width closes with the same ~0.5 uA margin: the supply/ground rails (at 0.0072 ohm/pitch, both ends) are not the limit. The limit would be rail quality: at 0.072 ohm/pitch even a single macro fails (section 4.2); that, not the number of columns, is what sets the largest viable width.")
    w("- **The bit-plane (20-column) mode is the worst electrical option**, not the safe one. Un-sensed bitlines are either floating - then they charge toward V_read through the cells that hang on the driven row line (LRS cells in ~150 ps, HRS cells in ~20 ns), drawing transient current through the shared row line and driver: "
      f"a data-dependent error of {c5['rows'][-2]['dyn_far_a']*1e6:.1f} uA at 200 ps even without coupling (cc 0: 2.2 uA at G = 0), and the budget closes only from {c5['rows'][-2]['earliest_closing_sampling_ps']} ps - or clamped to ground, which turns every idle cell into a DC load: each of the 8 reads then draws the full 160-column current, **8x the array energy** for the same result.")
    w("- **Decision: sense all 160 columns simultaneously (five macros, one pass).** Largest viable simultaneous width measured: **160** (no electrical limit reached; peak supply current {:.0f} mA at 0.1 V = {:.1f} mW for the nanosecond of the pulse, which is what the decoupling of section 5.1 has to deliver).".format(c5["rows"][0]["i_total_near_mA"], c5["rows"][0]["i_total_near_mA"] * 0.1))
    w("")
    w("## 8. Energy and latency for Phase 5")
    w("")
    w("### 8.1 Energy per inference, from 1E's read pattern")
    w("")
    w(f"1E issues one group read per (non-skipped count bit-row, group); the active rows a of each read is the popcount of the 8 count bits there. Phase 0's golden count vectors (240 DVS-Gesture samples) give that pattern exactly: **{en['reads_issued_per_inference']:,.0f} reads issued per inference, "
      f"of which {en['nonzero_reads_per_inference']:,.0f} have a > 0 ({100*(1-en['zero_read_fraction']):.0f}%), mean a = {en['mean_active_rows_per_nonzero_read']:.2f} rows per non-zero read, {en['active_row_reads_per_inference']:,.0f} active-row reads in total.** "
      "Energy = sum over reads of 5 x V_read x I_macro(G, a) x (T - tau) + a x 5 x C_WL x V_WL^2, with I_macro from the validated mesh (baseline rails, both-end drive, random weights), tau the pulse-start loss measured in the transients, and zero for a = 0 reads (no row is driven).")
    w("")
    w(md_table(["pulse length T", "array (nJ)", "word line (nJ)", "total (nJ / inference)", "per issued read (pJ)", "per non-zero read (pJ)", "% of NeuroHDC-small 3.01 uJ"],
               [[f"{float(T)*1e9:g} ns", f"{d['array_J']*1e9:.1f}", f"{d['wordline_J']*1e9:.1f}", f"{d['total_J']*1e9:.1f}", f"{d['per_issued_read_pJ']:.3f}", f"{d['per_nonzero_read_pJ']:.2f}", f"{d['total_J']/3.01e-6*100:.1f}%"] for T, d in en["energy_per_inference_J"].items()]))
    w("")
    w("These are the array only: the sense front-ends (input stage, comparators, reference DACs), the ladder-table and gain-correction memories' read energy, the row-driver and word-line buffer short-circuit/leakage, and the digital 1E blocks are not included. The pulse length T is set by the sense stage (not designed in 1C): "
      "the energy is linear in it, **so the sense stage's required integration time is the first number Phase 5 needs.** Energy is independent of g (it is set by the active-row reads); it depends on whether idle bitlines are clamped (section 7).")
    w("")
    w("### 8.2 Latency per group read")
    w("")
    w(f"Array: **0.13-0.16 ns** to settle to 0.1 uA (worst group, a = 8 or 4) and the crosstalk is below 0.1 uA from ~150 ps; sampling at 200 ps loses nothing (section 4.4). The comparator/ladder decision time [not designed] and the word-line rise (the next group's word lines can be raised during the current read; "
      f"58 fF at 1.1 V, ~60 ps with a 1 kohm buffer [ASSUM]) are additional. At NeuroHDC's 100 MHz clock a group read fits in a cycle with a factor ~50 to spare, which is why the cycle count (**{c5['rows'][0]['cycles']:,.0f} per inference = events + 1 cycle per group read**) rather than the array latency sets the inference time.")
    w("")
    w("### 8.3 Skipping groups with no active row (found, not asked for)")
    w("")
    nz = en["nonzero_reads_per_inference"]; rd = en["reads_issued_per_inference"]
    w(f"{100*en['zero_read_fraction']:.0f}% of the group reads 1E issues have a = 0 - there is nothing to drive. The array spends no energy on them, but 1E counts a cycle for each. The popcount a is known to the sequencer before the read is issued, so those reads could be skipped, giving "
      f"{nz:,.0f} reads and **{c5['rows'][0]['cycles']-(rd-nz):,.0f} cycles per inference (-{100*(rd-nz)/c5['rows'][0]['cycles']:.0f}%)**, a finer-grained skip than the all-or-nothing bit-row skip analysed in 1E section 7. This is a RTL change (not made: 1C writes no RTL) for Phase 5 / a 1E follow-up.")
    w("")
    w("## 9. Handoff to Phase 5")
    w("")
    w("| quantity | value | source / status |")
    w("|---|---|---|")
    w(f"| group reads per inference (g = 8, 160 columns at once) | {cm['reads_160']:,.0f} issued; {nz:,.0f} with a > 0 | 1E measured; this report section 8 |")
    w(f"| array energy per inference | {en['energy_per_inference_J']['5e-10']['total_J']*1e9:.0f} nJ (0.5 ns pulse) ... {en['energy_per_inference_J']['1e-08']['total_J']*1e9:.0f} nJ (10 ns); 1 ns: {en['energy_per_inference_J']['1e-09']['total_J']*1e9:.0f} nJ | [SIM], array + word line only |")
    w(f"| energy per group read (full array) | a = 8: near {en['i_macro_a8_near_far_A'][0]*5*0.1*(0.5e-9-en['tau_s'])*1e12:.2f} pJ, far {en['i_macro_a8_near_far_A'][1]*5*0.1*(0.5e-9-en['tau_s'])*1e12:.2f} pJ per 0.5 ns pulse (+ 0.35 pJ word line per active row x a) | [SIM]; scales with T |")
    w(f"| array latency per group read | 0.13-0.16 ns (settle), sample at 200 ps; + sense stage [TBD] | [SIM] |")
    w(f"| cycles per inference | {c5['rows'][0]['cycles']:,.0f} = {cm['c0']:,.0f} + reads (a = 0 reads could be skipped: ~{c5['rows'][0]['cycles']-(rd-nz):,.0f}) | 1E measured, fitted to 1 cycle |")
    w(f"| array area incl. periphery | {ab['total_mm2']:.2f} mm^2 ({area['sensitivity']['low']:.2f}-{area['sensitivity']['high']:.2f}); cell array {ab['parts_mm2']['cell_array']:.4f} mm^2 | [MODEL] + [ASSUM] densities |")
    w("| comparison basis (NeuroHDC-small, DVS-Gesture, 45 nm scaled) | 0.399 mm^2, 3.01 uJ / inference, 100 MHz, same 5 x (512 x 32) weight organisation | their Table III |")
    w(f"| peak supply current / power | {c5['rows'][0]['i_total_near_mA']:.0f} mA at 0.1 V (near group, a = 8) for the pulse | [SIM] |")
    w(f"| state to carry | {o['sizes']['0.1']['half_per_group_range']:,} bits ladder (half) + {gain_correction_bits():,} bits gain correction | section 3.3 |")
    w("")
    w("## 10. Handoff to 1D (write path)")
    w("")
    w("What the full-array work reveals for programming (the write itself is not simulated in 1C; 1B's write assumptions 10 pJ per pulse, 3 verify retries [ASSUM] are used only for scale):")
    w("")
    w(f"- **Rails and drivers are sized for read currents of ~70 mA; a row-parallel SET is the same order.** 160 cells x ~280 uA (the 20 F^2 ideal drive from 1A) = 45 mA per row if the whole row is set at once, 4.5 mA per driver (two per macro row): ~45 mV across a 10 ohm driver, small against a ~1-2 V SET, "
      "but R_DRV and the strap are **dimensioned for 0.1 V reads**: the write voltage path (driver type, rail voltage) is a 1D decision that the read-sized drivers do not settle.")
    w("- **Idle bitlines are not free.** A floating bitline is pulled toward the row potential through every cell on it (section 7): during a write the un-selected columns of the selected row must be held at the right potential by a clamp, otherwise they follow the row voltage on a ~150 ps (LRS) to ~20 ns (HRS) time constant and the *write disturb* depends on the neighbours' state; "
      "a clamp turns them into DC loads (current = row voltage / (R_dev + R_tx)) and that current is the programming current through the shared rail that 1D must budget.")
    w(f"- **Full-array program time and energy at 1B's assumptions:** {C.FULL_CELLS*C.ROWS_TOTAL*2:,} devices x 3 pulses x 10 pJ = {C.FULL_CELLS*C.ROWS_TOTAL*2*3*10e-12*1e6:.1f} uJ (1B: 4.9 uJ per refresh of the 163,840 devices); time = pulses x pulse width / parallelism: with a 100 ns pulse [ASSUM] row-parallel (320 devices per pulse) {C.ROWS_TOTAL*2*3*100e-9*1e3:.2f} ms, device-serial {C.FULL_CELLS*C.ROWS_TOTAL*2*3*100e-9*1e3:.0f} ms.")
    w("- **The ladder and gain tables are written once with the weights and depend on the achieved conductances** (the program-verify window sets sigma_lnG): a re-programmed array needs its thresholds recalibrated against the rails/row line, and the programmed weights must be placed so that the gain structure of section 3.3 stays valid (it assumes random weights; a pathological weight pattern is covered by the data-dependent terms only).")
    w("- Both devices of a cell sit on the same word line and row line: a SET of one device must not disturb the other (half-select) - the access transistors' leakage (1A: 4.6 pA at 27 C per transistor) bounds this for *unselected rows*.")
    w("")
    w("## 11. What changes in 1B's conclusions")
    w("")
    w("| 1B statement | 1C finding |")
    w("|---|---|")
    w("| 'at most 32 columns per row line, R_DRV <= 10 ohm; 160 = five 32-column macros' | 32 mesh columns = 16 cells. A true 32-cell macro (64 bitlines) needs drivers at both ends (or a 1-2 ohm single driver); R_DRV <= 10-20 ohm each. |")
    w("| 'the row-line gain is correctable by a per-column ladder scale' | it varies with the group: a per-column scale leaves ~5% (7% with rails); rank 2-3 correction needed (section 3.3). |")
    w("| 'centre tap: g* 8 -> 16 at sigma <= 0.05' (0.72 ohm/pitch) | holds at 0.5 ohm/pitch (to ~0.054) but only to ~0.022 at 0.72; the lumped model understated the within-group wire term 2.2x. Segmented-with-middle-node gives ~0.048 at 0.72. |")
    w("| 'whether 160 columns sense at once turns on droop and crosstalk' | it does not: both are small; what decides it is the idle-bitline behaviour of the narrow mode. |")
    w("| g = 8 margin 0.80 uA (6.4%) | 0.48 uA (3.9%) with the 1C terms; marginal. |")
    w("")
    w("## 12. Honest limits")
    w("")
    w("- The 1B and 1C margins (0.8 / 0.48 uA) are within the budget's Monte-Carlo and pattern-sampling error (a few percent of the limit): treat g = 8 as marginal. The data-dependent terms use 8 own x 40 other draws (maximum of a standard deviation over own patterns), and the gain-correction residual is near the sampling floor of its estimate (~0.05%).")
    w("- Transients assume an ideal supply at the rail pads, a linear access transistor (no charge injection), word line asserted before the pulse, no sense stage; the bitline/row/rail capacitances are the related-work 0.2 fF/pitch [ASSUM]. The pad network (R_pad 0.5 ohm, L_pad 100 pH) of the supply-dynamics study is assumed; its trend (ringing delays the usable sampling time, no data dependence) is the result, not the numbers.")
    w("- The crosstalk coupling fraction, bitline/row/rail resistance, driver and sense densities are assumptions (section 14); the *ranking* conclusions (rails and drivers dominate; rails needed ~0.0072 ohm/pitch fed from both ends; 160 at once) were checked across the swept ranges.")
    w("- C4's g* uses the same S1 / 'moderate' drift and 5-sigma spread as 1B; the Gaussian 5-sigma estimate is optimistic at small g (1B).")
    w("")
    w("## 13. Which findings are paper results")
    w("")
    w("| finding | verdict |")
    w("|---|---|")
    w("| Differential 2T2R: supply current is nearly data-independent, droop depends on the active-row count and is absorbed by the table | **Survives**, with the rail requirement it implies; a clean negative result against the single-ended intuition. |")
    w("| Row line of a 64-bitline macro needs drivers at both ends; per-column gain is not a constant but low-rank in (column, group) | **Survives** (validated mesh); the rank-3 residual is near the sampling floor. |")
    w("| Idle floating bitlines disturb the shared row line (the narrow sensing mode is worse than the wide one) | **Survives as a design finding** - transient-simulated; sensitive to the cell/bitline C assumption. |")
    w("| Centre tap pays only at small sigma, and less than a lumped model says | **Survives** (mesh-measured at the true positions). |")
    w("| Periphery (row drivers, sense) is >90% of the array area | **Qualified**: every periphery size is an assumed density; the ranking is robust across the low/high range, the absolute mm^2 is not. |")
    w("")
    w("## 14. TO BE DETERMINED (updated list)")
    w("")
    w("- **sigma_lnG** [ASSUM, swept]: still sets g (1B); needs measured device data (1D).")
    w("- **Drift exponent / spread** [ASSUM, swept] (1B).")
    w("- **Bitline / row-line resistance per pitch (0.5-0.72 ohm), driver resistance** [ASSUM]; the 1C requirement is stated against them. **Rail resistance and the metal that realises it** (0.0072 ohm/pitch needs a 0.56 um strap at an assumed 0.02 ohm/sq) [ASSUM].")
    w("- **Bitline, row-line and coupling capacitance** (0.2 fF/pitch total, cc 0.25-0.75) [ASSUM]; **sense-node capacitance** 5 fF [ASSUM].")
    w("- **The sense stage**: input-referred current noise (1 uA, 1 sigma [ASSUM]), integration time, energy per read, the 8-comparator flash assumed in the area; **the pulse length T and the decoupling it needs** (the DC results use ideal pads; the dynamic study assumes R_pad, L_pad).")
    w("- **Layout densities** behind the area (driver um^2 per um of width, comparator/sense/DAC areas, SRAM um^2/bit, decap density) [ASSUM, low/mid/high].")
    w("- **Word-line timing and switching** (channel-charge injection, WL rise) - not modelled.")
    w("- **SET current and the write path** (1D); the compact model `rram.va` is still uncompiled (OpenVAF not installed).")
    w("- **ReRAM read-current temperature coefficient** (1A/1B limitation).")
    w("- **Group-read skipping of a = 0 reads** (RTL change, Phase 5 / 1E follow-up); **the event count of NeuroHDC's evaluation samples** for a like-for-like latency comparison.")
    w("")
    w("## 15. Reproduce")
    w("")
    w("```")
    w("python -m pytest tests -q                                  # 64 tests (16 new, tests/test_scaleup.py)")
    w("python -m wire.validate_mesh_ext --n 300                   # extended mesh vs ngspice")
    w("python -m validate.gate_cap                                # access-transistor gate capacitance (PTM card)")
    w("python -m scaleup.run_column && python -m scaleup.run_accumulate && python -m scaleup.run_controls && python -m scaleup.table_size     # C1a-c")
    w("python -m scaleup.run_energy_latency && python -m scaleup.analyze_c1d                                                              # C1d (long: ~25 min)")
    w("python -m scaleup.run_rowline && python -m scaleup.run_rowline_ext && python -m scaleup.run_droop && python -m scaleup.gain_matrix  # C2 DC")
    w("python -m scaleup.run_crosstalk && python -m scaleup.analyze_crosstalk && python -m scaleup.run_crosstalk_bitplane && python -m scaleup.run_supply_dynamics   # C2 transients")
    w("python -m scaleup.c2_budget                                                                                                        # the budget re-closed")
    w("python -m scaleup.run_array && python -m scaleup.run_array_transient && python -m scaleup.energy_inference && python -m scaleup.area # C3")
    w("python -m scaleup.run_variants && python -m scaleup.run_variants_breakeven                                                         # C4")
    w("python -m scaleup.c5_decision                                                                                                      # C5")
    w("python -m scaleup.figures && python -m scaleup.make_report                                                                         # figures and this report")
    w("```")
    RP.REPORTS.mkdir(parents=True, exist_ok=True)
    RP.REPORT_1C.write_text("\n".join(L) + "\n")
    print("wrote", RP.REPORT_1C, len(L), "lines")


if __name__ == "__main__":
    main()
