"""1F: the sense front-end - array port model, transistor-level channel, budget machinery, energy accounting, PDN. The ngspice tests are skipped when ngspice is not installed; the result-file tests check
internal consistency of the committed JSON (they are regenerated by the commands in the 1F report)."""
import json

import numpy as np
import pytest

import device.constants as C
import paths as RP
from spice.runner import ngspice_available

ngspice = pytest.mark.skipif(not ngspice_available(), reason="ngspice not installed")
have = lambda p: pytest.mark.skipif(not p.exists(), reason=f"{p.name} not generated")


def test_port_model_reproduces_1c_far_group_step():
    from sense import port as P
    far = P.worst_step(P.FAR_POS0)
    assert 33.5e-6 < far < 35.0e-6                   # 1C mesh: 34.1 uA before row-line / rail losses; the port model 34.3 uA
    ip, im = P.levels(P.FAR_POS0)
    assert np.all(np.diff(ip - im) < 0) or np.all(np.diff(ip - im) > 0)     # monotone levels


@ngspice
def test_conveyor_channel_copies_the_array_current():
    from sense import mc, port as P
    from sense.cal import DESIGN
    dz = mc.Design(**DESIGN)
    ip, im = P.levels(P.FAR_POS0)
    a, b = mc.i_channels(dz, 1, P.FAR_POS0)
    assert a == pytest.approx(ip[1], rel=0.05) and b == pytest.approx(im[1], rel=0.06)      # nominal copy within 6% of the ideal-virtual-ground levels (the gain is calibrated per column)


@ngspice
def test_copy_device_mismatch_moves_the_channel_current():
    from sense import cal, mc, port as P
    dz = mc.Design(**cal.DESIGN)
    nom = np.array([mc.i_channels(dz, m, P.FAR_POS0) for m in range(9)])
    assert nom.shape == (9, 2)
    dv = {n: 0.01 for n in dz.devices() if n.startswith("M2")}          # 10 mV on the copy devices
    mis = np.array([mc.i_channels(dz, m, P.FAR_POS0, dv) for m in range(9)])
    assert abs(mis - nom).max() > 1e-6                                   # a real effect (uA scale), not numerical noise
    assert abs(mis / nom - 1).max() < 0.5                                # and a gain error, not a different circuit


@have(RP.SENSE / "calibration_mc.json")
def test_calibration_needs_two_parameters_and_drifts_with_temperature():
    c = json.loads((RP.SENSE / "calibration_mc.json").read_text())
    assert c["raw"]["rms_uA"] > 20                                       # uncalibrated mismatch is far above the 12 uA budget limit
    g, go = c["gain_only"]["27"], c["gain_and_offset"]["27"]
    assert go["sigma_worst_point_uA"] < 0.5 < g["sigma_worst_point_uA"]  # one parameter is not enough, two are
    r = [c["gain_and_offset"][f"{t:g}"]["rms_uA"] for t in c["temps"]]
    assert r == sorted(r)                                                # the residual grows with the temperature offset from calibration


@have(RP.SENSE / "topology_comparison.json")
def test_only_the_conveyor_holds_the_virtual_ground_at_equal_power():
    t = json.loads((RP.SENSE / "topology_comparison.json").read_text())
    row = lambda nm, s: [r for r in t["rows"] if r["topology"] == nm and r["ota_scale"] == s and r["group"] == "far" and abs(r["T"] - 1e-9) < 1e-15][0]
    assert row("b", 1)["step_ratio_min"] > 0.7
    for nm, s in (("a", 1), ("d", 1), ("d2", 1)):
        assert row(nm, s)["step_ratio_min"] < 0.65
    assert t["supply"]["c x1"][1] > 0.5                                  # (c) forces the node to ~0.54 V: the row supply would have to be 0.64 V


def test_budget_machinery_reproduces_the_1c_baseline():
    from sense import budget_1f as B
    b = B.closure(8, 0.10, None, comp_sigma_a=1e-6, n=500)
    assert b["margin_left_a"] == pytest.approx(0.476e-6, abs=0.03e-6)    # 1C report: 0.48 uA of 12.20 uA
    assert b["worst_group"] == "far"


def test_front_end_terms_enter_the_budget_in_quadrature_at_five_sigma():
    from sense import budget_1f as B
    t = B.fe_terms(dict(far=1e-6, near=1e-6), dict(far=0.0, near=0.0), d_t_k=0.0, thr_rel=0.0)
    assert t["far"][0][2] == pytest.approx(5e-6) and all(x[1] == "random" for x in t["far"])


@have(RP.SENSE / "energy_per_inference_1f.json")
def test_energy_components_sum_and_sense_dominates():
    from sense import energy_1f as E
    e = E.energy(0.46, 1e-9, 0.3e-9, 8)
    assert e["total_J"] == pytest.approx(e["array_J"] + e["wordline_J"] + e["sense_bias_J"] + e["decision_J"] + e["threshold_J"], rel=1e-12)
    assert e["sense_bias_J"] > e["array_J"]                              # the front-end, not the array, sets the energy
    assert E.energy(0.46, 2e-9, 0.3e-9, 8)["total_J"] > e["total_J"]     # linear in the pulse length


@have(RP.PDN / "pdn_sweep.json")
def test_pdn_droop_falls_with_decoupling_and_charge_scales_with_current():
    p = json.loads((RP.PDN / "pdn_sweep.json").read_text())
    sel = sorted([x for x in p if x["t_pulse"] == 1e-9 and x["r_d"] == 0.1 and x["stagger"] == 0.0 and x.get("i_scale", 1.0) == 1.0 and x["c_dec"] > 0], key=lambda x: x["c_dec"])
    d = [x["droop_max_mV"] for x in sel]
    assert d == sorted(d, reverse=True)
    q = 0.0692 * 1e-9                                                    # 69.2 mA x 1 ns: the droop at the largest C is bounded below by Q / C
    assert sel[-1]["droop_max_mV"] * 1e-3 >= 0.5 * q / sel[-1]["c_dec"]


def test_a_zero_reads_are_the_largest_group_of_issued_reads():
    rc = json.loads((RP.SENSE / "read_counts.json").read_text()) if (RP.SENSE / "read_counts.json").exists() else None
    if rc is None:
        pytest.skip("read_counts.json not generated")
    r = rc["8"]
    assert r["reads_nonzero"] / r["reads_issued"] == pytest.approx(0.381, abs=0.002)    # 1C: 62% of issued reads have a = 0
